#ifndef __GetOrg_DLG__
#define __GetOrg_DLG__

/**
@file
Subclass of cleanGetOrg_DLG, which is generated by wxFormBuilder.
*/

#include "cleanFRM.h"

//// end generated include
#include "cleanAll.h"
/** Implementing cleanGetOrg_DLG */
class GetOrg_DLG : public cleanGetOrg_DLG
{
	protected:
		// Handlers for cleanGetOrg_DLG events.
		void GetOrg_DLGOnClose(     wxCloseEvent&   event );
		void dOrgName_LBOnSelect( wxCommandEvent& event );
		void dLoadOrg_OnClick(   wxCommandEvent& event );
		void dSaveOrg_OnClick(   wxCommandEvent& event );
		void  dNewOrg_OnClick(   wxCommandEvent& event );
		void  dSetOrg_OnClick(   wxCommandEvent& event );
		void  dUseOrg_OnClick(   wxCommandEvent& event );
		void  dDelOrg_OnClick(   wxCommandEvent& event );
	public:
		/** Constructor */
		GetOrg_DLG( wxWindow* parent );
	//// end generated class members
	private:
		// Variables
		xStr  orgIni;
		bool  isModified;
		// Methods
		s8    dNewOrg( ORG* org   );
		s8    dSetOrg( s8   index, ORG* org  );
		ORG*  dGetOrg( s8   index );
		ORG*  dGetOrg( void );
		void dShowOrg( void );
		void dSaveOrg( void );
		void dLoadOrg( void );
};

#endif // __GetOrg_DLG__
