#include "hex2_wxFB.h"
#include "hex2_global.h"
#include "hex2_db.h"
#include "hexG_db.h"
#include "hexDB_main.h"
#include <array>

#ifndef HEXGUI_G
#define HEXGUI_G

/**
@file
Subclass of HexGUI, which is generated by wxFormBuilder.
*/
const int NO_OF_PANELS = 19;
class G : public HexGUI
{
	protected:
		/** Handlers for HexGUI events. */
		void G_OnIdle( wxIdleEvent& event );
		void HexGUI_TB_OnToolExec( wxCommandEvent& event );
		void HexList_LB_OnSelect( wxCommandEvent& event );
		void HexState_B_OnClick( wxCommandEvent& event );
		void HexBinExec_B_OnClick( wxCommandEvent& event );
		void HexBinHack_B_OnClick( wxCommandEvent& event );
		void HexFAdd_B_OnClick( wxCommandEvent& event );
		void HexConvert_B_OnClick( wxCommandEvent& event );
		void HexHack_TC_OnSelect( wxTreeEvent& event );
		void HexCode_TC_OnSelect( wxTreeEvent& event );
	public:
		G( wxWindow* parent, bool user = false ); ~G();
		/** Internal Stuff */
		bool m_bCwd;
		hexGui m_gui;
		// List
		bool	m_bListCfg;
		// GUI
		wxPanel* m_aPanels[ NO_OF_PANELS ];
		void	ShowPanels( int inMode, bool inCfg );
		void	UpdatePanels();
		void	UpdateList( hexDB& db, Text name = getGlobalName() );
		void	UpdateTheme( Text name = wxT(""), si32 size = 22 );
		bool	Find( HANDLE& hApp, BinF& hBin );
		bool	Read( HANDLE& hApp, BinF& hBin );
		bool	Read( HANDLE& hApp, BinF& hBin, wxTextCtrl* oText );
		// Shared DB Functions
		bool	CheckFilesT( hexDB& db, Text& path, Text& leaf, Text& ext, Text& subP );
		bool	CheckDirs( hexDB& db, Text& path, Text& leaf );
		void	ShowData( hexDB& db );
		bool	EditHasInvalidName( Text& name );
		void	EditData( hexDB& db );
		/** Sessions **/
		void	LoadStateD( State& obj );
		void	ShowStateD( State& obj );
		/** Organisations **/
		void	ShowOrgD( Org* obj );
		bool	EditOrgD( Org* obj );
		/** Platforms */
		void	ShowPfmD( Pfm& obj );
		bool	EditPfmD( Pfm& obj );
		/** Binaries ( Applications / Files ) */
		void	ShowBinD( Bin& obj );
		bool	EditBinD( Bin& obj );
		void	ShowRamD( Ram& obj );
		void	EditRamD( Ram& obj );
		/** Profiles ( Hacklists ) */
		void	ShowPflD( Pfl& obj );
		bool	EditPflD( Pfl& obj );
		void	ShowRegion( ui32 region );
		ui32	EditRegion( void );
		/** Formats **/
		void	ShowFormat( Format& obj );
		/** Hacklist */
		void	ListHcks( Hacks& data );
		void	ShowHack( Hacks& data, int hackNo = 0 );
		bool	EditHack( Hacks& data, int hackNo = 0 );
		void	ShowCode( Code& obj );
		bool	EditCode( Code& obj );
		void	ShowCodeValue( wxTextCtrl* tbox, Code& obj, int v );
		void	EditCodeValue( wxTextCtrl* tbox, Code& obj, int v );
};

#endif
