#ifndef HEXGUI_G
#define HEXGUI_G

/**
@file
Subclass of HexGUI, which is generated by wxFormBuilder.
*/

#include "hex2_wxFB.h"
#include "hex2_global.h"
#include "hex2_db.h"
#include "hexG_db.h"
#include "hexDB_main.h"

enum
{
	HEX_LOAD_SAVE2FILE = 0,
	HEX_LOAD_SAVE2TEMP,
	HEX_LOAD_LIST,
	HEX_LOAD_COUNT
};
const si08 g_iPanelCount = 13;
const Text g_tIniCfg	 = wxT("[Settings]");
const Text g_tIniThemes	 = wxT("[Themes]");
class G : public HexGUI
{
	protected:
		/** Handlers for HexGUI events. */
		void HexGUI_TB_OnToolExec( wxCommandEvent& event );
		void HexList_LB_OnSelect( wxCommandEvent& event );
		void HexState_B_OnClick( wxCommandEvent& event );
		void HexHack_TC_OnSelect( wxTreeEvent& event );
		void HexCode_TC_OnSelect( wxTreeEvent& event );
	public:
		G( wxWindow* parent ); ~G();
		/** Internal Stuff */
		bool m_bCwd;
		// List
		bool	m_bListCfg;
		si32	m_siListNow;
		hexDB	m_db;
		// GUI
		wxPanel* m_aPanels[ g_iPanelCount ];
		void	UpdatePanels();
		void	UpdateList( hexDB& db, LBox* lb, Text name = getGlobalName() );
		void	UpdateTheme( Text name = wxT(""), si32 size = 22 );
		bool	Find( HANDLE& hApp, wxFile& hBin );
		bool	Read( HANDLE& hApp, wxFile& hBin );
		bool	Read( HANDLE& hApp, wxFile& hBin, wxTextCtrl* oText );
		// Shared DB Functions
		bool	CheckFilesT( hexDB& db, Text& path, Text& leaf, Text& ext, Text& subP );
		bool	CheckDirs( hexDB& db, Text& path, Text& leaf );
		bool	LoadData( hexDB& db, TxtA& data, Text& nowP, Text& tmpP, Text& name, bool isFileTmp = false, bool isTempTmp = true );
		void	LoadData( hexDB& db, LBox* lbox, int doAct = HEX_LOAD_SAVE2TEMP, Text name = getGlobalName() );
		void	ShowData( hexDB& db );
		/** Sessions **/
		State	LoadStates( State& old, CfgF& file, CfgF& temp, TxtA& data, Text name, bool isFileTmp, bool isTempTmp );
		void	LoadStateD( State& obj, Text& key, Text& val, bool isTmpFile = false );
		void	LoadStateD( State& obj, CfgF& file );
		void	LoadStateD( State& obj );
		void	SaveStateD( State& obj, CfgF& file, bool isTmpFile = false );
		void	ShowStateD( State& obj );
		/** Organisations **/
		Org		LoadOrgs( Org& old, CfgF& file, CfgF& temp, TxtA& data, Text name, bool isFileTmp, bool isTempTmp );
		void	LoadOrgD( Org& obj, Text& key, Text& val, bool isTmpFile = true );
		void	SaveOrgD( Org& obj, CfgF& file, bool isTmpFile = true );
		void	ShowOrgD( Org* obj );
		/** Platforms */
		Pfm		LoadPfms( Pfm& old, TxtF& file, TxtF& temp, TxtA& data, Text name, bool addObj, bool isFileTmp, bool isTempTmp );
		void	LoadPfmD( Pfm& obj, TxtF& file, bool isTmpFile = true );
		void	SavePfmD( Pfm& obj, TxtF& file, bool isTmpFile = true );
		void	ShowPfmD( Pfm& obj );
		/** Binaries ( Applications / Files ) */
		Bin		LoadBins( Bin& old, TxtF& file, TxtF& temp, TxtA& data, Text name, bool addObj, bool isFileTmp, bool isTempTmp );
		void	LoadBinD( Bin& obj, TxtF& file, bool isTmpFile = true );
		void	SaveBinD( Bin& obj, TxtF& file, bool isTmpFile = true );
		void	ShowBinD( Bin& obj );
		void	ShowRamD( Ram& obj );
		/** Profiles ( Hacklists ) */
		ui32	CheckRegion( Text region );
		Text	CheckRegion( ui32 region );
		Pfl		LoadPfls( Pfl& old, TxtF& file, TxtF& temp, TxtA& data, Text name, bool addObj, bool isFileTmp, bool isTempTmp );
		void	LoadPflD( Pfl& obj, TxtF& file, bool isTmpFile = true );
		void	SavePflD( Pfl& obj, TxtF& file, bool isTmpFile = true );
		void	ShowPflD( Pfl& obj );
		/** Hacklist */
		void	ListHcks( Hacks& dat );
		void	ShowHack( Hack& obj );
		void	ShowCode( Code& obj );
};

#endif
