#ifndef HEXGUI_G
#define HEXGUI_G

/**
@file
Subclass of HexGUI, which is generated by wxFormBuilder.
*/

#include "hexGUI_wxFB.h"
#include "hexGUI_global.hpp"
#include "hexGUI_db.hpp"
#include "hexDB_main.hpp"

class G : public HexGUI
{
	protected:
		/** Handlers for HexGUI events. */
		void HexGUI_TB_OnToolExec( wxCommandEvent& event );
		void HexList_LB_OnSelect( wxCommandEvent& event );
	public:
		G( wxWindow* parent );
		~G( void );
		/** Internal Stuff */
		enum
		{
			HEX_LIST_ORG,
			HEX_LIST_PFM,
			HEX_LIST_BIN,
			HEX_LIST_APPS,
			HEX_LIST_FIND,
			HEX_LIST_OUT,
			HEX_LIST_PFL,
			HEX_LIST_HCK,
			HEX_LIST_COUNT
		};
		bool m_ListCfg;
		TxtA m_ListCfgNames;
		bool m_ListCwd;
		int m_ListNow;
		int m_ListOld;
		Vect< wxPanel* >m_List_Ps;
		int m_Org;
		int m_Pfm;
		int m_Bin;
		int m_Pfl;
		int m_Hck;
		int m_Cde;
		Org m_org;
		Pfm m_pfm;
		Bin m_bin;
		Pfl m_pfl;
		Hack m_hck;
		Text m_hexPath;
		Text m_orgPath;
		Text m_iniCfgPath;
		Text m_iniOrgPath;
		Text m_iniThemePath;
		void UpdatePanels( void );
		void UpdateTheme( Text name = wxT("") );
		bool UpdatePflT( TxtF& now, TxtF& old, Text& path );
		bool UpdateHckT( TxtF& now, TxtF& old, Text& path );
		bool Search( HANDLE& hApp, wxFile& hBin );
		bool Read( HANDLE& hApp, wxFile& hBin );
		bool Read( HANDLE& hApp, wxFile& hBin, wxTextCtrl* oText );
		bool ListTabs( void );
		bool CheckPaths( bool& isCfg, Text& path, Text& hckP, TxtA& txtA );
		bool CheckTmpBin( Text& path, int inMode = -1 );
		bool LoadDatT( void );
		bool SaveDatT( void );
		bool LoadDatB( void* vDat, ui08& aSize, int inMode = -1 );
		bool SaveDatB( void* vDat, ui08  aSize, int inMode = -1 );
		/** Organisations */
		bool LoadOrgT( CfgF& file, Text& path );
		bool ListOrgs( void );
		void ShowOrgD( int s = 0 );
		/** Platforms */
		void ShowPfmD( int s = 0 );
		bool LoadPfmT( CfgF& file, Text& path );
		/** Binarys ( Applications / Files ) */
		bool LoadBinT( CfgF& file, Text& path );
		void ShowBinD( int s = 0 );
		bool ListApps( void );
		bool ListBins( void );
		/** Profiles ( Hacklists ) */
		void ShowPflD( int s = 0 );
		bool LoadPflT( TxtF& file, Text& path );
		/** Hacklist */
		bool ListHacks( void );
		bool ListHacks( Hack* vect, ui08& aSize );
		bool ShowHack(  Hack* vect, ui08& aSize, Hack& hack, ui16 index );
		/** Codelist (for individual Hacks) */
};

#endif
